#服务器端口号
server:
  port: 8080
  servlet:
    context-path: /seatcheck

#mybaits对应的实体类包
mybatis:
  type-aliases-package: com.resellbook.resellbook.entity

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resellbook?useUnicode=true&characterEncoding=utf-8&useSSL=false&&allowPublicKeyRetrieval=true
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver

#redis配置
redis:
host: 127.0.0.1       #Redis 地址
port: 6379            #Redis 端口号
database: 0           #Redis 索引（0~15，默认为0）
timeout: 1000         #Redis 连接的超时时间
#password: 123456      #Redis 密码，如果没有就默认不配置此参数
lettuce:              #使用 lettuce 连接池
pool:
max-active: 20    #连接池最大连接数（使用负值表示没有限制）
max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
min-idle: 0       #连接池中的最大空闲连接
max-idle: 10      #连接池中的最小空闲连接
